/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as IncrementalityRouteImport } from './routes/incrementality'
import { Route as IndexRouteImport } from './routes/index'

const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IncrementalityRoute = IncrementalityRouteImport.update({
  id: '/incrementality',
  path: '/incrementality',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incrementality': typeof IncrementalityRoute
  '/planner': typeof PlannerRoute
  '/segments': typeof SegmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incrementality': typeof IncrementalityRoute
  '/planner': typeof PlannerRoute
  '/segments': typeof SegmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incrementality': typeof IncrementalityRoute
  '/planner': typeof PlannerRoute
  '/segments': typeof SegmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/incrementality' | '/planner' | '/segments'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/incrementality' | '/planner' | '/segments'
  id: '__root__' | '/' | '/incrementality' | '/planner' | '/segments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncrementalityRoute: typeof IncrementalityRoute
  PlannerRoute: typeof PlannerRoute
  SegmentsRoute: typeof SegmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incrementality': {
      id: '/incrementality'
      path: '/incrementality'
      fullPath: '/incrementality'
      preLoaderRoute: typeof IncrementalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncrementalityRoute: IncrementalityRoute,
  PlannerRoute: PlannerRoute,
  SegmentsRoute: SegmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
